import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import UserProvider from "@/context/user.provider";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "hawkers-accessories",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <Providers>
      <html lang="en">
      <body className="font">
        
        <UserProvider>
          <Toaster />

          {children}
        </UserProvider>
      </body>
    </html>
  </Providers>
  );
}
