import React from "react";

export const metadata = {
  title: "hawkers-accessories | Home",
  description: "Generated by create next app",
};
const layout = ({ children }) => {
  return <div>
    {children}
    </div>;
};

export default layout;
