
import Footer from "@/Components/Shared/Footer/Footer";
import MobileNavbar from "@/Components/Shared/MobileNavbar/MobileNavbar";
import Navbar from "@/Components/Shared/Navbar/Navbar";
import React from "react";

export const metadata = {
  title: "hawkers-accessories | Home",
  description: "Generated by create next app",
};
const layout = ({ children }) => {
  return <div className="min-h-screen">
    <Navbar/>
    <MobileNavbar/>
    {children}
    <Footer/>
    </div>;
};

export default layout;
 